// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using userprofile.persistence;

namespace userprofile.persistence.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    partial class UserProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("userprofile.entities.Models.AdminUserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<bool>("IsActivated");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20);

                    b.Property<string>("ReferredBy")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AdminUserModel");

                    b.HasData(
                        new { Id = 1L, DateCreated = new DateTime(2019, 8, 3, 10, 17, 22, 345, DateTimeKind.Utc), EmailAddress = "superadmin@wegopay.com", Firstname = "Super", IsActivated = true, IsActive = true, IsAdmin = true, Lastname = "Admin", Password = "admin123@@@***", PhoneNo = "08022334455", ReferredBy = "Site Owner" }
                    );
                });

            modelBuilder.Entity("userprofile.entities.Models.UserActivationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivatedOn");

                    b.Property<string>("ActivationCode");

                    b.Property<bool>("ComfirmedActivation");

                    b.Property<DateTime>("SentOn");

                    b.Property<long>("UserModelId");

                    b.HasKey("Id");

                    b.ToTable("UserActivationModel");
                });

            modelBuilder.Entity("userprofile.entities.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Firstname");

                    b.Property<bool>("IsActivated");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Lastname");

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<byte[]>("PaswordHash");

                    b.Property<string>("PhoneNo");

                    b.Property<string>("ReferredBy");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
